[event]
title = "네이버쇼핑 ─ 아트윈도 ─ 테마"
url = "https://shopping.naver.com/art/event"
entrySelector = "ul.XNP0X_c-6J li"
titleSelector = "a strong"
linkSelector = "a"
contentSelector = "p.S7nFgeJfh8"
imageSelector = "div img"
waitUntil = "networkidle"

[event_news]
title = "네이버쇼핑 ─ 아트윈도 ─ 소식"
url = "https://shopping.naver.com/art/event?filter=NEWS"
entrySelector = "ul.XNP0X_c-6J li"
titleSelector = "a strong"
linkSelector = "a"
contentSelector = "p.S7nFgeJfh8"
imageSelector = "div img"
waitUntil = "networkidle"

[event_special]
title = "네이버쇼핑 ─ 아트윈도 ─ 기획전"
url = "https://shopping.naver.com/art/event?filter=SPECIAL_EVENT"
entrySelector = "ul.XNP0X_c-6J li"
titleSelector = "a strong"
linkSelector = "a"
contentSelector = "p.S7nFgeJfh8"
imageSelector = "div img"
waitUntil = "networkidle"